import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Inari</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            welcome to my world
          </p>
          <div>
            <a
              href="http://www.yyoga.top/"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              Young
            </a>
          </div>
        </div>

        <div className={styles.center}>
          Inari
        </div>

        <div className={styles.grid}>
          <Link href="/chat" className={styles.card}>
            <h2 className={inter.className}>
              Chat<span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Actually you will talk to chat-gpt
            </p>
          </Link>
          <a className={styles.card}>
            <h2 className={inter.className}>
              Me <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              You can find more about me
            </p>
          </a>

          <a className={styles.card}>
            <h2 className={inter.className}>
              Family <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              You can find more about my family
            </p>
          </a>

          <a className={styles.card}>
            <h2 className={inter.className}>
              Protugal <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              {"ola I'm here"}
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
